name: Update Fleet teams
run-name: ${{ github.actor}} is updating teams
on: [push]
jobs:
  update-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install fleetctl
        run: npm install -g fleetctl
        shell: bash

      - name: Configure fleetctl
        run: fleetctl config set --address ${{ secrets.FLEET_URL }} --token ${{ secrets.FLEET_API_TOKEN }}
        shell: bash

      - name: apply teams
        run: |
          cat teams/*.yml > teams.yml
          fleetctl apply -f teams.yml
        shell: bash